# Generated by Django 4.2.7 on 2026-01-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking_app.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='parking_app.campus'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='nearest_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_app.building'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parking_app.assignment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='parking_app.campus'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parking_app.assignment'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='new_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parking_app.parkingslot'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='previous_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parking_app.parkingslot'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_app.parkingslot'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_app.schedule'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['status'], name='parking_app_status_2c56d3_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['slot_type'], name='parking_app_slot_ty_2b9380_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('parking_lot', 'slot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='parkinglot',
            unique_together={('campus', 'name')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='parking_app_user_id_20c6b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'code')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'status'], name='parking_app_user_id_0d8a53_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['parking_slot', 'status'], name='parking_app_parking_e3ec1e_idx'),
        ),
    ]
