# Generated by Django 4.2.7 on 2026-01-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_notified', models.BooleanField(default=False, help_text='Whether user was notified about no-show')),
                ('reason', models.CharField(blank=True, help_text='Reason provided by user (optional)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_record', to='parking_app.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_shows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'No-Show Tracking',
                'verbose_name_plural': 'No-Show Tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='parking_app_user_id_0d29e0_idx')],
            },
        ),
    ]
