# Generated by Django 4.2.7 on 2026-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_noshowtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for user to confirm (30 mins after assignment)', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When user confirmed arrival', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='User confirmed arrival at parking lot'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-Show - Slot Released')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_confirmed', 'status'], name='parking_app_is_conf_851d6e_idx'),
        ),
    ]
