# Generated by Django 4.2.7 on 2026-03-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('subscription_type', models.CharField(choices=[('basic', 'Basic - Standard Parking'), ('premium', 'Premium - Priority Parking'), ('vip', 'VIP - Reserved Premium Spots')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(help_text='Comma-separated list of features for this package')),
                ('max_active_reservations', models.IntegerField(default=1)),
                ('priority_slot_access', models.BooleanField(default=False)),
                ('reserved_spots', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Package',
                'verbose_name_plural': 'Payment Packages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('basic', 'Basic - Standard Parking'), ('premium', 'Premium - Priority Parking'), ('vip', 'VIP - Reserved Premium Spots')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paypal_transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('duration_months', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paypal_transaction_id'], name='users_app_p_paypal__b520f0_idx'), models.Index(fields=['user', 'status'], name='users_app_p_user_id_d195d6_idx')],
            },
        ),
    ]
